implicit_wait=10
googleUrl=https://www.google.com/
way2automationUrl1=https://www.way2automation.com/
way2automationUrl2=https://way2automation.com/way2auto_jquery/index.php
timesOfIndiaUrl=https://timesofindia.indiatimes.com/poll.cms
jqueryslider=https://jqueryui.com/slider/
jqueryresize=https://jqueryui.com/resizable/
jquerydroppable=https://jqueryui.com/droppable/
rightClick=http://deluxe-menu.com/popup-mode-sample.html
alertbox=https://mail.rediff.com/cgi-bin/login.cgi
gmail=https://www.gmail.com/